import QuarterPills from '../QuarterPills'
import { Loading, ErrorState, EmptyState, NotAvailablePanel } from '../States'
import { useKpiTracker } from '../../hooks/useDashboardData'
import { gbp, num, pct } from '../../data/format'
import { FY_TARGETS } from '../../data/thresholds'

// Board top-line in the agreed order: MQLs → SQLs → MQL→SQL → Closed opps →
// Influenced pipeline → Closed-won → CPL. Live where the store supports it.
export default function Board() {
  const q = useKpiTracker()

  return (
    <>
      <div className="page-head">
        <div>
          <div className="page-title">Board <span className="accent">Pack</span></div>
          <div className="page-sub">Executive top-line · agreed order · FY2026</div>
        </div>
        <QuarterPills />
      </div>

      {q.isLoading && <Loading />}
      {q.isError && <ErrorState error={q.error} />}
      {q.data && !q.data.hasData && <EmptyState />}
      {q.data && q.data.hasData && <TopLine f={q.data.funnel} />}

      {/* Narrative is produced by the AI layer — left intact, not fabricated */}
      <NotAvailablePanel
        title="Board Narrative · H1 2026"
        what="The board narrative"
        why="Generated by the AI layer (not yet wired). The figures above are live."
      />
    </>
  )
}

function TopLine({ f }) {
  return (
    <>
      <div className="kpis cols-4">
        <Card n="1 · MQLs" v={num(f.mql)} t={`FY ${num(FY_TARGETS.mqls)}`} />
        <Card n="2 · SQLs" v={num(f.sql)} t={`FY ${num(FY_TARGETS.sqls)}`} />
        <Card n="3 · MQL → SQL Rate" v={pct(f.sql, f.mql)} t="derived" />
        <Card n="4 · Closed Opportunities" v="—" t="not available yet" na />
      </div>
      <div className="kpis cols-3">
        <Card n="5 · Influenced Pipeline" v={gbp(f.pipeline)} t={`FY ${gbp(FY_TARGETS.influencedPipeline)}`} />
        <Card n="6 · Closed-Won Value" v={gbp(f.closedWon)} t={`FY margin ${gbp(FY_TARGETS.influencedMargin)}`} />
        <Card n="7 · Cost per Lead" v="—" t="spend = 0" na />
      </div>
    </>
  )
}

const Card = ({ n, v, t, na }) => (
  <div className="kpi">
    <div className="kpi-head">
      <div className={`kpi-icn${na ? ' amber' : ''}`}>
        <svg className="icon icon-lg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" /></svg>
      </div>
      <span className={`tl ${na ? 'neu' : 'green'}`}><span className="tl-dot" />{na ? 'n/a' : 'live'}</span>
    </div>
    <div className="kpi-label">{n}</div>
    <div className="kpi-val">{v}</div>
    <div className="kpi-sub"><span className="kpi-target">{t}</span></div>
  </div>
)
